project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!_*.qmd"  # Exclude files starting with underscore
    - "LMAs/*.qmd"  # Explicitly include LMA files

website:
  title: "| Active Monitoring of Oxytocin Research Evidence"
  favicon: "amore.favicon.ico"
  open-graph: true
  page-footer: 
    center: 
      - icon: github
        href: https://github.com/iaiversen/AMORE-webpage
        aria-label: GitHub 
      - text: "Behavioral Neuroendocrinology Lab"
        href: https://www.sv.uio.no/psi/english/research/groups/bnl/index.html
  navbar:
    search: true
    logo: "logo.unfinished.jpg"
    right:
      - text: "Living Meta-Analysis"
        href: Living_meta-analysis_Directory.qmd 
      - text: "Contact"
        href: contact.qmd
      - text: "Guidelines"
        href: guidelines.qmd
      - text: "Standardized framework"
        href: Standardization.qmd
      - text: "Resources"
        href: Resources.qmd
      - text: "About"
        href: about.qmd
      - text: "Home"
        href: index.qmd
format:
  html:
    theme: 
      - yeti
      - styles.scss
    css: styles.scss
    include-in-header:
      # Add metadata tags for better SEO and data extraction
      text: |
        <meta name="description" content="Active Monitoring of Oxytocin Research Evidence (AMORE) is a platform for living meta-analyses in oxytocin research.">
        <meta name="keywords" content="oxytocin, living meta-analysis, systematic review, behavioral outcomes, biobehavioral, AMORE">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
# Uncomment when deploying Shiny:
# resources:
#   - shiny
# execute:
#   freeze: auto