project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!_*.qmd"  # Exclude files starting with underscore
    - "pages/*.qmd"  # Include pages folder
    - "LMAs/*.qmd"  # Explicitly include LMA files

website:
  title: "Active Monitoring of Oxytocin Research Evidence"
  favicon: "assets/favicons/favicon.ico"  
  open-graph: true
  page-footer: 
    center: 
      - icon: github
        href: https://github.com/iaiversen/AMORE-webpage
        aria-label: GitHub 
      - text: "Behavioral Neuroendocrinology Lab"
        href: https://www.sv.uio.no/psi/english/research/groups/bnl/index.html
  navbar:
    search: true
    logo: "assets/images/logo.unfinished_nowhite- Copy.png"
    right:
      - text: "Living Meta-Analysis"
        href: pages/Living_meta-analysis_Directory.qmd  
      - text: "Contact"
        href: pages/contact.qmd  
      - text: "Guidelines"
        href: pages/guidelines.qmd  
      - text: "Standardized framework"
        href: pages/Standardization.qmd  
      - text: "Resources"
        href: pages/Resources.qmd  
      - text: "About"
        href: pages/about.qmd  
      - text: "Home"
        href: index.qmd  

format:
  html:
    theme: 
      - yeti
      - assets/styles/styles.scss  
    css: assets/styles/styles.scss
    include-in-header:
      text: |
        <meta name="description" content="Active Monitoring of Oxytocin Research Evidence (AMORE) is a platform for living meta-analyses in oxytocin research.">
        <meta name="keywords" content="oxytocin, living meta-analysis, systematic review, behavioral outcomes, biobehavioral, AMORE">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="theme-color" content="#0A2A5E">
        <link rel="apple-touch-icon" sizes="180x180" href="assets/favicons/apple-touch-icon.png">  # CHANGED
        <link rel="icon" type="image/png" sizes="96x96" href="assets/favicons/favicon-96x96.png">  # CHANGED
        <link rel="manifest" href="assets/favicons/site.webmanifest">  # CHANGED
# Uncomment when deploying Shiny:
# resources:
#   - shiny
# execute:
#   freeze: auto