project:
  type: website
  output-dir: _site
website:
  title: "| Active Monitoring of Oxytocin Research Evidence"
  open-graph: true
  page-footer: 
    center: 
      - icon: github
        href: https://github.com/iaiversen/AMORE-webpage
        aria-label: GitHub 
      - text: "Behavioral Neuroendocrinology Lab"
        href: https://www.sv.uio.no/psi/english/research/groups/bnl/index.html
  navbar:
    search: true
    logo: "logo.unfinished.jpg"
    right:
      - text: "Living Meta-Analysis"
        href: LMA_placeholder.qmd # Replace with LMA.shiny.qmd when going live 
      - text: "Contact"
        href: contact.qmd
      - text: "Guidelines"
        href: guidelines.qmd
      - text: "Standardization goals"
        href: Standardization.qmd
      - text: "About"
        href: about.qmd
      - text: "Home"
        href: index.qmd
format:
  html:
    theme: 
      - yeti
      - styles.scss
    css: styles.scss
# Uncomment when deploying Shiny:
# resources:
#   - shiny
# execute:
#   freeze: auto