---
format:
  html:
    theme: 
      - ../styles.scss
    css: ../styles.scss 
    page-layout: full
    title-block-banner: false 
    title-block-style: none 
---

::: {.contact-container}

::: {.contact-section}
## Connect With Us 
If you are interested in publishing your living meta-analysis on our platform, you can connect with us through our contact form. Whether you have questions about conducting your analysis within our standardized framework, want to discuss potential plans or protocols, or have any other inquiries - feel free to reach out. There is no commitment required.

::: {.contact-buttons}
[Contact Form](https://nettskjema.no/a/492183){.primary-button target="_blank"}
:::

## Publishing Your Meta-Analysis
If you're interested in publishing your Living Meta-Analysis on AMORE, we encourage you to:

- Review our [Guidelines](/guidelines.qmd) on how to get your living meta analysis published on the AMORE platform
- Check our [Standardization Goals](/Standardization.qmd) for specific requirements
- Review the [Checklist](/Protocol_checklist.html) for creating a Living Meta-Analysis Protocol
- [Use the contact form](https://nettskjema.no/a/492183){target="_blank"} to submit your initial proposal


:::
:::