[build]
  publish = "_site"
 

[[redirects]]
  from = "/*"
  to = "/login"
  status = 401
  conditions = {Role = ["anonymous"]}

[[redirects]]
  from = "/login"
  to = "/login"
  status = 200

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  conditions = {Role = ["member"]}
