---
title: "Research tools and resources" 
format:
  html:
    theme: 
      - yeti
      - styles.scss
    css: styles.scss
---

::: {.title-space}
::: 

## Checklist for creating AMORE project proposal {#resourcepage} 

::: {.resource-list}
::: {.resource-item}
When creating a project proposal for a Living Meta-Analysis in AMORE, it is essential to include all necessary information to ensure a smooth review and approval process. The following checklist outlines the key components that should be included in your project proposal:

This protocol checklist tool serves to help ensure all necessary information in the project proposal form is included. When planning your project use this checklist to see what information we require. This will streamline the process of entering the required details to the “propose your project” form when you are ready to submit

[Access the Protocol Checklist Tool](Protocol_checklist.html){.resource-link}
:::
::: 

## Additional Resources {#resourcepage}

::: {.resource-list}
::: {.resource-item}
### PRISMA for Living Systematic Reviews {#prisma}

PRISMA for Living Systematic Reviews (LSR) is an extension of the PRISMA statement that provides guidance on reporting living systematic reviews and meta-analyses. It includes a checklist and flow diagram to help researchers ensure they are following best practices in their reporting.

[Visit PRISMA-Statement.org Website](http://prisma-statement.org/lsr){.resource-link target="_blank"}
:::

::: {.resource-item}
### PROSPERO {#prospero}

PROSPERO is specifically designed for registering systematic review protocols focused on health related research It provides a standardized format for documenting review methods before they begin.

[Visit PROSPERO](https://www.crd.york.ac.uk/prospero/){.resource-link target="_blank"}
:::

::: {.resource-item}
### Open Science Framework (OSF) {#osf}

The Open Science Framework (OSF) is a free and open-source platform that supports researchers in managing their projects, sharing their data, and collaborating with others. It provides tools for pre-registration, data sharing, and project management, making it easier for researchers to conduct and share their work transparently. It is developed by the Center for Open Science (COS).

[Visit OSF](https://osf.io/){.resource-link target="_blank"}
:::

::: {.resource-item}
### Retraction Watch {#retraction-watch}

Tracking retractions as a window into the scientific process. This resource monitors and reports on retractions of scientific papers.

[Visit Retraction Watch](https://retractionwatch.com/){.resource-link target="_blank"}
:::

::: {.resource-item}
### Zotero {#zotero}

Reference management software that helps you collect, organize, and cite research. Zotero informs when articles in your libraries have been retracted or corrected, and it can help you keep track of your references and citations.

[Visit Zotero](https://www.zotero.org/){.resource-link target="_blank"}
:::
:::